#!/usr/bin/with-contenv bash

# Fetch site or update existing
if [[ ! -d /config/www/Dashboard/.git ]]; then
  echo '-----------------------'
  echo '| Installing Organizr |'
  echo '-----------------------'
  git clone -b v2-develop https://github.com/causefx/Organizr /config/www/Dashboard
elif [[ -d /config/www/Dashboard/.git ]]; then
  echo '-----------------------'
  echo '|  Updating Organizr  |'
  echo '-----------------------'
  cd /config/www/Dashboard || return
  git reset --hard origin/v2-develop
  git pull --rebase
fi

# Set Permissions
chown -R abc:abc \
	/config
