#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*           This image has been deprecated           *
*                                                    *
*          Please use the official image at          *
*     https://hub.docker.com/r/organizr/organizr     *
*                                                    *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'